[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

# https://github.com/Mellbourn/lsColorsToToml
[filetype]
rules = [
  { url = "*", is = "block", fg = "#b58900", bg = "#eee8d5", bold = true },
  { url = "*", is = "char", fg = "#b58900", bg = "#eee8d5", bold = true },
  { url = "*/", fg = "#268bd2", bold = true },
  { url = "*", is = "exec", fg = "#859900", bold = true },
  { url = "*", is = "link", fg = "#2aa198", bold = true },
  { url = "*", is = "orphan", fg = "#dc322f", bg = "#eee8d5", bold = true },
  { url = "*", is = "fifo", fg = "#b58900", bg = "#eee8d5", bold = true },
  { url = "*", is = "sock", fg = "#d33682", bg = "#eee8d5", bold = true },
  { url = "*", is = "sticky" },
  { url = "*.1", fg = "#839496" },
  { url = "*.a", fg = "#839496" },
  { url = "*.c", fg = "#839496" },
  { url = "*.d", fg = "#839496" },
  { url = "*.h", fg = "#839496" },
  { url = "*.m", fg = "#839496" },
  { url = "*.o", fg = "#586e75" },
  { url = "*.p", fg = "#839496" },
  { url = "*.r", fg = "#839496" },
  { url = "*.t", fg = "#839496" },
  { url = "*.v", fg = "#839496" },
  { url = "*.z", fg = "#dc322f", bold = true },
  { url = "*.7z", fg = "#dc322f", bold = true },
  { url = "*.ai", fg = "#d33682" },
  { url = "*.as", fg = "#839496" },
  { url = "*.bc", fg = "#586e75" },
  { url = "*.bz", fg = "#dc322f", bold = true },
  { url = "*.cc", fg = "#839496" },
  { url = "*.cp", fg = "#839496" },
  { url = "*.cr", fg = "#839496" },
  { url = "*.cs", fg = "#839496" },
  { url = "*.db", fg = "#dc322f", bold = true },
  { url = "*.di", fg = "#839496" },
  { url = "*.el", fg = "#839496" },
  { url = "*.ex", fg = "#839496" },
  { url = "*.fs", fg = "#839496" },
  { url = "*.go", fg = "#839496" },
  { url = "*.gv", fg = "#839496" },
  { url = "*.gz", fg = "#dc322f", bold = true },
  { url = "*.ha", fg = "#839496" },
  { url = "*.hh", fg = "#839496" },
  { url = "*.hi", fg = "#586e75" },
  { url = "*.hs", fg = "#839496" },
  { url = "*.jl", fg = "#839496" },
  { url = "*.js", fg = "#839496" },
  { url = "*.ko", fg = "#839496" },
  { url = "*.kt", fg = "#839496" },
  { url = "*.la", fg = "#586e75" },
  { url = "*.ll", fg = "#839496" },
  { url = "*.lo", fg = "#586e75" },
  { url = "*.ma", fg = "#d33682" },
  { url = "*.mb", fg = "#d33682" },
  { url = "*.md", fg = "#839496" },
  { url = "*.mk", fg = "#839496" },
  { url = "*.ml", fg = "#839496" },
  { url = "*.mn", fg = "#839496" },
  { url = "*.nb", fg = "#839496" },
  { url = "*.nu", fg = "#839496" },
  { url = "*.pl", fg = "#839496" },
  { url = "*.pm", fg = "#839496" },
  { url = "*.pp", fg = "#839496" },
  { url = "*.ps", fg = "#cb4b16" },
  { url = "*.py", fg = "#839496" },
  { url = "*.rb", fg = "#839496" },
  { url = "*.rm", fg = "#d33682", bold = true },
  { url = "*.rs", fg = "#839496" },
  { url = "*.sh", fg = "#839496" },
  { url = "*.so", fg = "#839496" },
  { url = "*.td", fg = "#839496" },
  { url = "*.ts", fg = "#839496" },
  { url = "*.ui", fg = "#839496" },
  { url = "*.vb", fg = "#839496" },
  { url = "*.wv", fg = "#2aa198" },
  { url = "*.xz", fg = "#dc322f", bold = true },
  { url = "*FAQ", fg = "#839496" },
  { url = "*.3ds", fg = "#d33682" },
  { url = "*.3fr", fg = "#d33682" },
  { url = "*.3mf", fg = "#d33682" },
  { url = "*.adb", fg = "#839496" },
  { url = "*.ads", fg = "#839496" },
  { url = "*.aif", fg = "#2aa198" },
  { url = "*.amf", fg = "#d33682" },
  { url = "*.ape", fg = "#2aa198" },
  { url = "*.apk", fg = "#dc322f", bold = true },
  { url = "*.ari", fg = "#d33682" },
  { url = "*.arj", fg = "#dc322f", bold = true },
  { url = "*.arw", fg = "#d33682" },
  { url = "*.asa", fg = "#839496" },
  { url = "*.asm", fg = "#839496" },
  { url = "*.aux", fg = "#586e75" },
  { url = "*.avi", fg = "#d33682", bold = true },
  { url = "*.awk", fg = "#839496" },
  { url = "*.bag", fg = "#dc322f", bold = true },
  { url = "*.bak", fg = "#586e75" },
  { url = "*.bat", fg = "#839496" },
  { url = "*.bay", fg = "#d33682" },
  { url = "*.bbl", fg = "#586e75" },
  { url = "*.bcf", fg = "#586e75" },
  { url = "*.bib", fg = "#839496" },
  { url = "*.bin", fg = "#dc322f", bold = true },
  { url = "*.blg", fg = "#586e75" },
  { url = "*.bmp", fg = "#d33682" },
  { url = "*.bsh", fg = "#839496" },
  { url = "*.bst", fg = "#839496" },
  { url = "*.bz2", fg = "#dc322f", bold = true },
  { url = "*.c++", fg = "#839496" },
  { url = "*.cap", fg = "#d33682" },
  { url = "*.cfg", fg = "#839496" },
  { url = "*.cgi", fg = "#839496" },
  { url = "*.clj", fg = "#839496" },
  { url = "*.com", fg = "#839496" },
  { url = "*.cpp", fg = "#839496" },
  { url = "*.cr2", fg = "#d33682" },
  { url = "*.cr3", fg = "#d33682" },
  { url = "*.crw", fg = "#d33682" },
  { url = "*.css", fg = "#839496" },
  { url = "*.csv", fg = "#839496" },
  { url = "*.csx", fg = "#839496" },
  { url = "*.cxx", fg = "#839496" },
  { url = "*.dae", fg = "#d33682" },
  { url = "*.dcr", fg = "#d33682" },
  { url = "*.dcs", fg = "#d33682" },
  { url = "*.deb", fg = "#dc322f", bold = true },
  { url = "*.def", fg = "#839496" },
  { url = "*.dll", fg = "#839496" },
  { url = "*.dmg", fg = "#dc322f", bold = true },
  { url = "*.dng", fg = "#d33682" },
  { url = "*.doc", fg = "#cb4b16" },
  { url = "*.dot", fg = "#839496" },
  { url = "*.dox", fg = "#839496" },
  { url = "*.dpr", fg = "#839496" },
  { url = "*.drf", fg = "#d33682" },
  { url = "*.dxf", fg = "#d33682" },
  { url = "*.eip", fg = "#d33682" },
  { url = "*.elc", fg = "#839496" },
  { url = "*.elm", fg = "#839496" },
  { url = "*.epp", fg = "#839496" },
  { url = "*.eps", fg = "#d33682" },
  { url = "*.erf", fg = "#d33682" },
  { url = "*.erl", fg = "#839496" },
  { url = "*.exe", fg = "#839496" },
  { url = "*.exr", fg = "#d33682" },
  { url = "*.exs", fg = "#839496" },
  { url = "*.fbx", fg = "#d33682" },
  { url = "*.fff", fg = "#d33682" },
  { url = "*.fls", fg = "#586e75" },
  { url = "*.flv", fg = "#d33682", bold = true },
  { url = "*.fnt", fg = "#6c71c4" },
  { url = "*.fon", fg = "#6c71c4" },
  { url = "*.fsi", fg = "#839496" },
  { url = "*.fsx", fg = "#839496" },
  { url = "*.gif", fg = "#d33682" },
  { url = "*.git", fg = "#586e75" },
  { url = "*.gpr", fg = "#d33682" },
  { url = "*.gvy", fg = "#839496" },
  { url = "*.h++", fg = "#839496" },
  { url = "*.hda", fg = "#d33682" },
  { url = "*.hip", fg = "#d33682" },
  { url = "*.hpp", fg = "#839496" },
  { url = "*.htc", fg = "#839496" },
  { url = "*.htm", fg = "#839496" },
  { url = "*.hxx", fg = "#839496" },
  { url = "*.ico", fg = "#d33682" },
  { url = "*.ics", fg = "#cb4b16" },
  { url = "*.idx", fg = "#586e75" },
  { url = "*.igs", fg = "#d33682" },
  { url = "*.iiq", fg = "#d33682" },
  { url = "*.ilg", fg = "#586e75" },
  { url = "*.img", fg = "#dc322f", bold = true },
  { url = "*.inc", fg = "#839496" },
  { url = "*.ind", fg = "#586e75" },
  { url = "*.ini", fg = "#839496" },
  { url = "*.inl", fg = "#839496" },
  { url = "*.ino", fg = "#839496" },
  { url = "*.ipp", fg = "#839496" },
  { url = "*.iso", fg = "#dc322f", bold = true },
  { url = "*.jar", fg = "#dc322f", bold = true },
  { url = "*.jpg", fg = "#d33682" },
  { url = "*.jsx", fg = "#839496" },
  { url = "*.jxl", fg = "#d33682" },
  { url = "*.k25", fg = "#d33682" },
  { url = "*.kdc", fg = "#d33682" },
  { url = "*.kex", fg = "#cb4b16" },
  { url = "*.kra", fg = "#d33682" },
  { url = "*.kts", fg = "#839496" },
  { url = "*.log", fg = "#586e75" },
  { url = "*.ltx", fg = "#839496" },
  { url = "*.lua", fg = "#839496" },
  { url = "*.m3u", fg = "#2aa198" },
  { url = "*.m4a", fg = "#2aa198" },
  { url = "*.m4v", fg = "#d33682", bold = true },
  { url = "*.mdc", fg = "#d33682" },
  { url = "*.mef", fg = "#d33682" },
  { url = "*.mid", fg = "#2aa198" },
  { url = "*.mir", fg = "#839496" },
  { url = "*.mkv", fg = "#d33682", bold = true },
  { url = "*.mli", fg = "#839496" },
  { url = "*.mos", fg = "#d33682" },
  { url = "*.mov", fg = "#d33682", bold = true },
  { url = "*.mp3", fg = "#2aa198" },
  { url = "*.mp4", fg = "#d33682", bold = true },
  { url = "*.mpg", fg = "#d33682", bold = true },
  { url = "*.mrw", fg = "#d33682" },
  { url = "*.msi", fg = "#dc322f", bold = true },
  { url = "*.mtl", fg = "#d33682" },
  { url = "*.nef", fg = "#d33682" },
  { url = "*.nim", fg = "#839496" },
  { url = "*.nix", fg = "#839496" },
  { url = "*.nrw", fg = "#d33682" },
  { url = "*.obj", fg = "#d33682" },
  { url = "*.obm", fg = "#d33682" },
  { url = "*.odp", fg = "#cb4b16" },
  { url = "*.ods", fg = "#cb4b16" },
  { url = "*.odt", fg = "#cb4b16" },
  { url = "*.ogg", fg = "#2aa198" },
  { url = "*.ogv", fg = "#d33682", bold = true },
  { url = "*.orf", fg = "#d33682" },
  { url = "*.org", fg = "#839496" },
  { url = "*.otf", fg = "#6c71c4" },
  { url = "*.otl", fg = "#d33682" },
  { url = "*.out", fg = "#586e75" },
  { url = "*.pas", fg = "#839496" },
  { url = "*.pbm", fg = "#d33682" },
  { url = "*.pcx", fg = "#d33682" },
  { url = "*.pdf", fg = "#cb4b16" },
  { url = "*.pef", fg = "#d33682" },
  { url = "*.pgm", fg = "#d33682" },
  { url = "*.php", fg = "#839496" },
  { url = "*.pid", fg = "#586e75" },
  { url = "*.pkg", fg = "#dc322f", bold = true },
  { url = "*.png", fg = "#d33682" },
  { url = "*.pod", fg = "#839496" },
  { url = "*.ppm", fg = "#d33682" },
  { url = "*.pps", fg = "#cb4b16" },
  { url = "*.ppt", fg = "#cb4b16" },
  { url = "*.pro", fg = "#839496" },
  { url = "*.ps1", fg = "#839496" },
  { url = "*.psd", fg = "#d33682" },
  { url = "*.ptx", fg = "#d33682" },
  { url = "*.pxn", fg = "#d33682" },
  { url = "*.pyc", fg = "#586e75" },
  { url = "*.pyd", fg = "#586e75" },
  { url = "*.pyo", fg = "#586e75" },
  { url = "*.qoi", fg = "#d33682" },
  { url = "*.r3d", fg = "#d33682" },
  { url = "*.raf", fg = "#d33682" },
  { url = "*.rar", fg = "#dc322f", bold = true },
  { url = "*.raw", fg = "#d33682" },
  { url = "*.rpm", fg = "#dc322f", bold = true },
  { url = "*.rst", fg = "#839496" },
  { url = "*.rtf", fg = "#cb4b16" },
  { url = "*.rw2", fg = "#d33682" },
  { url = "*.rwl", fg = "#d33682" },
  { url = "*.rwz", fg = "#d33682" },
  { url = "*.sbt", fg = "#839496" },
  { url = "*.sql", fg = "#839496" },
  { url = "*.sr2", fg = "#d33682" },
  { url = "*.srf", fg = "#d33682" },
  { url = "*.srw", fg = "#d33682" },
  { url = "*.stl", fg = "#d33682" },
  { url = "*.stp", fg = "#d33682" },
  { url = "*.sty", fg = "#586e75" },
  { url = "*.svg", fg = "#d33682" },
  { url = "*.swf", fg = "#d33682", bold = true },
  { url = "*.swp", fg = "#586e75" },
  { url = "*.sxi", fg = "#cb4b16" },
  { url = "*.sxw", fg = "#cb4b16" },
  { url = "*.tar", fg = "#dc322f", bold = true },
  { url = "*.tbz", fg = "#dc322f", bold = true },
  { url = "*.tcl", fg = "#839496" },
  { url = "*.tex", fg = "#839496" },
  { url = "*.tga", fg = "#d33682" },
  { url = "*.tgz", fg = "#dc322f", bold = true },
  { url = "*.tif", fg = "#d33682" },
  { url = "*.tml", fg = "#839496" },
  { url = "*.tmp", fg = "#586e75" },
  { url = "*.toc", fg = "#586e75" },
  { url = "*.tsx", fg = "#839496" },
  { url = "*.ttf", fg = "#6c71c4" },
  { url = "*.txt", fg = "#839496" },
  { url = "*.typ", fg = "#839496" },
  { url = "*.usd", fg = "#d33682" },
  { url = "*.vcd", fg = "#dc322f", bold = true },
  { url = "*.vim", fg = "#839496" },
  { url = "*.vob", fg = "#d33682", bold = true },
  { url = "*.vsh", fg = "#839496" },
  { url = "*.wav", fg = "#2aa198" },
  { url = "*.wma", fg = "#2aa198" },
  { url = "*.wmv", fg = "#d33682", bold = true },
  { url = "*.wrl", fg = "#d33682" },
  { url = "*.x3d", fg = "#d33682" },
  { url = "*.x3f", fg = "#d33682" },
  { url = "*.xlr", fg = "#cb4b16" },
  { url = "*.xls", fg = "#cb4b16" },
  { url = "*.xml", fg = "#839496" },
  { url = "*.xmp", fg = "#839496" },
  { url = "*.xpm", fg = "#d33682" },
  { url = "*.xvf", fg = "#d33682" },
  { url = "*.yml", fg = "#839496" },
  { url = "*.zig", fg = "#839496" },
  { url = "*.zip", fg = "#dc322f", bold = true },
  { url = "*.zsh", fg = "#839496" },
  { url = "*.zst", fg = "#dc322f", bold = true },
  { url = "*TODO", fg = "#839496", bold = true },
  { url = "*hgrc", fg = "#839496" },
  { url = "*.avif", fg = "#d33682" },
  { url = "*.bash", fg = "#839496" },
  { url = "*.braw", fg = "#d33682" },
  { url = "*.conf", fg = "#839496" },
  { url = "*.dart", fg = "#839496" },
  { url = "*.data", fg = "#d33682" },
  { url = "*.diff", fg = "#839496" },
  { url = "*.docx", fg = "#cb4b16" },
  { url = "*.epub", fg = "#cb4b16" },
  { url = "*.fish", fg = "#839496" },
  { url = "*.flac", fg = "#2aa198" },
  { url = "*.h264", fg = "#d33682", bold = true },
  { url = "*.hack", fg = "#839496" },
  { url = "*.heif", fg = "#d33682" },
  { url = "*.hgrc", fg = "#839496" },
  { url = "*.html", fg = "#839496" },
  { url = "*.iges", fg = "#d33682" },
  { url = "*.info", fg = "#839496" },
  { url = "*.java", fg = "#839496" },
  { url = "*.jpeg", fg = "#d33682" },
  { url = "*.json", fg = "#839496" },
  { url = "*.less", fg = "#839496" },
  { url = "*.lisp", fg = "#839496" },
  { url = "*.lock", fg = "#586e75" },
  { url = "*.make", fg = "#839496" },
  { url = "*.mojo", fg = "#839496" },
  { url = "*.mpeg", fg = "#d33682", bold = true },
  { url = "*.nims", fg = "#839496" },
  { url = "*.opus", fg = "#2aa198" },
  { url = "*.orig", fg = "#586e75" },
  { url = "*.pptx", fg = "#cb4b16" },
  { url = "*.prql", fg = "#839496" },
  { url = "*.psd1", fg = "#839496" },
  { url = "*.psm1", fg = "#839496" },
  { url = "*.purs", fg = "#839496" },
  { url = "*.raku", fg = "#839496" },
  { url = "*.rlib", fg = "#586e75" },
  { url = "*.sass", fg = "#839496" },
  { url = "*.scad", fg = "#839496" },
  { url = "*.scss", fg = "#839496" },
  { url = "*.step", fg = "#d33682" },
  { url = "*.tbz2", fg = "#dc322f", bold = true },
  { url = "*.tiff", fg = "#d33682" },
  { url = "*.toml", fg = "#839496" },
  { url = "*.usda", fg = "#d33682" },
  { url = "*.usdc", fg = "#d33682" },
  { url = "*.usdz", fg = "#d33682" },
  { url = "*.webm", fg = "#d33682", bold = true },
  { url = "*.webp", fg = "#d33682" },
  { url = "*.woff", fg = "#6c71c4" },
  { url = "*.xbps", fg = "#dc322f", bold = true },
  { url = "*.xlsx", fg = "#cb4b16" },
  { url = "*.yaml", fg = "#839496" },
  { url = "*stdin", fg = "#586e75" },
  { url = "*v.mod", fg = "#839496" },
  { url = "*.blend", fg = "#d33682" },
  { url = "*.cabal", fg = "#839496" },
  { url = "*.cache", fg = "#586e75" },
  { url = "*.class", fg = "#586e75" },
  { url = "*.cmake", fg = "#839496" },
  { url = "*.ctags", fg = "#586e75" },
  { url = "*.dylib", fg = "#839496" },
  { url = "*.dyn_o", fg = "#586e75" },
  { url = "*.gcode", fg = "#839496" },
  { url = "*.ipynb", fg = "#839496" },
  { url = "*.mdown", fg = "#839496" },
  { url = "*.patch", fg = "#839496" },
  { url = "*.rmeta", fg = "#586e75" },
  { url = "*.scala", fg = "#839496" },
  { url = "*.shtml", fg = "#839496" },
  { url = "*.swift", fg = "#839496" },
  { url = "*.toast", fg = "#dc322f", bold = true },
  { url = "*.woff2", fg = "#6c71c4" },
  { url = "*.xhtml", fg = "#839496" },
  { url = "*Icon\r", fg = "#586e75" },
  { url = "*LEGACY", fg = "#839496" },
  { url = "*NOTICE", fg = "#839496" },
  { url = "*README", fg = "#839496" },
  { url = "*go.mod", fg = "#839496" },
  { url = "*go.sum", fg = "#586e75" },
  { url = "*passwd", fg = "#839496" },
  { url = "*shadow", fg = "#839496" },
  { url = "*stderr", fg = "#586e75" },
  { url = "*stdout", fg = "#586e75" },
  { url = "*.bashrc", fg = "#839496" },
  { url = "*.config", fg = "#839496" },
  { url = "*.dyn_hi", fg = "#586e75" },
  { url = "*.flake8", fg = "#839496" },
  { url = "*.gradle", fg = "#839496" },
  { url = "*.groovy", fg = "#839496" },
  { url = "*.ignore", fg = "#839496" },
  { url = "*.matlab", fg = "#839496" },
  { url = "*.nimble", fg = "#839496" },
  { url = "*COPYING", fg = "#839496" },
  { url = "*INSTALL", fg = "#839496" },
  { url = "*LICENCE", fg = "#839496" },
  { url = "*LICENSE", fg = "#839496" },
  { url = "*TODO.md", fg = "#839496", bold = true },
  { url = "*VERSION", fg = "#839496" },
  { url = "*.alembic", fg = "#d33682" },
  { url = "*.desktop", fg = "#839496" },
  { url = "*.gemspec", fg = "#839496" },
  { url = "*.mailmap", fg = "#839496" },
  { url = "*Doxyfile", fg = "#839496" },
  { url = "*Makefile", fg = "#839496" },
  { url = "*TODO.txt", fg = "#839496", bold = true },
  { url = "*setup.py", fg = "#839496" },
  { url = "*.DS_Store", fg = "#586e75" },
  { url = "*.cmake.in", fg = "#839496" },
  { url = "*.fdignore", fg = "#839496" },
  { url = "*.kdevelop", fg = "#839496" },
  { url = "*.markdown", fg = "#839496" },
  { url = "*.rgignore", fg = "#839496" },
  { url = "*.tfignore", fg = "#839496" },
  { url = "*CHANGELOG", fg = "#839496" },
  { url = "*COPYRIGHT", fg = "#839496" },
  { url = "*README.md", fg = "#839496" },
  { url = "*bun.lockb", fg = "#586e75" },
  { url = "*configure", fg = "#839496" },
  { url = "*.gitconfig", fg = "#839496" },
  { url = "*.gitignore", fg = "#839496" },
  { url = "*.localized", fg = "#586e75" },
  { url = "*.scons_opt", fg = "#586e75" },
  { url = "*.timestamp", fg = "#586e75" },
  { url = "*CODEOWNERS", fg = "#839496" },
  { url = "*Dockerfile", fg = "#839496" },
  { url = "*INSTALL.md", fg = "#839496" },
  { url = "*README.txt", fg = "#839496" },
  { url = "*SConscript", fg = "#839496" },
  { url = "*SConstruct", fg = "#839496" },
  { url = "*.cirrus.yml", fg = "#839496" },
  { url = "*.gitmodules", fg = "#839496" },
  { url = "*.synctex.gz", fg = "#586e75" },
  { url = "*.travis.yml", fg = "#839496" },
  { url = "*INSTALL.txt", fg = "#839496" },
  { url = "*LICENSE-MIT", fg = "#839496" },
  { url = "*MANIFEST.in", fg = "#839496" },
  { url = "*Makefile.am", fg = "#839496" },
  { url = "*Makefile.in", fg = "#586e75" },
  { url = "*.applescript", fg = "#839496" },
  { url = "*.fdb_latexmk", fg = "#586e75" },
  { url = "*.webmanifest", fg = "#839496" },
  { url = "*CHANGELOG.md", fg = "#839496" },
  { url = "*CONTRIBUTING", fg = "#839496" },
  { url = "*CONTRIBUTORS", fg = "#839496" },
  { url = "*appveyor.yml", fg = "#839496" },
  { url = "*configure.ac", fg = "#839496" },
  { url = "*.bash_profile", fg = "#839496" },
  { url = "*.clang-format", fg = "#839496" },
  { url = "*.editorconfig", fg = "#839496" },
  { url = "*CHANGELOG.txt", fg = "#839496" },
  { url = "*.gitattributes", fg = "#839496" },
  { url = "*.gitlab-ci.yml", fg = "#839496" },
  { url = "*CMakeCache.txt", fg = "#586e75" },
  { url = "*CMakeLists.txt", fg = "#839496" },
  { url = "*LICENSE-APACHE", fg = "#839496" },
  { url = "*pyproject.toml", fg = "#839496" },
  { url = "*CODE_OF_CONDUCT", fg = "#839496" },
  { url = "*CONTRIBUTING.md", fg = "#839496" },
  { url = "*CONTRIBUTORS.md", fg = "#839496" },
  { url = "*.sconsign.dblite", fg = "#586e75" },
  { url = "*CONTRIBUTING.txt", fg = "#839496" },
  { url = "*CONTRIBUTORS.txt", fg = "#839496" },
  { url = "*requirements.txt", fg = "#839496" },
  { url = "*package-lock.json", fg = "#586e75" },
  { url = "*CODE_OF_CONDUCT.md", fg = "#839496" },
  { url = "*.CFUserTextEncoding", fg = "#586e75" },
  { url = "*CODE_OF_CONDUCT.txt", fg = "#839496" },
  { url = "*azure-pipelines.yml", fg = "#839496" },
]
